### PR TITLE
Refactoring & tests

### PR DESCRIPTION
**Pull request by burgercode**
- Ignored DS_Store
- Added one test and removed useless code
- Changed packages structure (i.e. moved ProjectList and ProjectDetail)
- Changed buildToolsVersion

### CODE REVIEW

**Comment by alemannosara** [comment]
It a good idea to implement the onDestroyView method and also to make sure that bindings made with butter knife are indeed unbind at the end of the fragment « life ». Good job! 

Your branch name is « codeClimate fix ». I read the code but I don’t really see where the fix may be. What was the problem actually?

**Comment by burgercode** [comment]
Thanks! After some long investigations, I think that CodeClimate isn't working because travis cannot find some files related to Butterknife at the end of the script. Thus CodeClimate doesn't receive the data needed to make a report. To overall goal of this branch is to remove everything that could cause problem and make CodeClimate work again, including organizing the packages correctly, change the build tool version and remove butterknife from multiple files.

**Comment by burgercode** [comment]
**Stop using Butterknife**
@alemannosara @KnightEther @nazliuzuner @fmutlu 
Hello everyone! As you can see above, Butterknife seems to cause multiple problems. From breaking CodeClimate, reducing our code coverage without any good reasons and since we don't really know what Butterknife does under the hood, Butterknife is slowing down our projects rather that speed it up. I suggest that we stop using it, It will resolve multiple bugs and make CodeClimate work again. 

**Details** 
Butterknife seems to generate news files, i.e. NAMEOFFILE__viewBinding, and the same thing for unbinding, during build phase. 

- We do not have control on them and cannot test them -> reduced code coverage.
- For some reasons, Travis tries to open those files at the end of the script, but the files doesn't exists anymore -> CodeClimate bug

Furthermore, stoping using Butterknife isn't too hard, it's juste a few characters more per view binding.

**Comment by alemannosara** [comment]
Indeed, I noticed these new files appearing and I also decided to stop using ButterKnife on my branch as it was impossible to test the parts where I use them. 

Thanks for fixing this code climate problem! I hope our code coverage is fine now.

To me, you can merge. I totally agree with your code and comments on ButterKnife.

**Pull request merged**
