### PR TITLE
Update design

### PR DESCRIPTION
**Pull request by KnightEther**

### CODE REVIEW

**Comment by alemannosara** [comment]
I have just seen the sprint backlog and Nazli seems to be assigned to do the tabs so it is ok for me.

**Comment by KnightEther** [comment]
Yes indeed it is the modify view PR

**Comment by alemannosara** [comment]
I have just noticed that the button « edit » on the references is not visible anymore 😢

**Comment by KnightEther** [comment]
Close (done in Uniform design update PR)

**Pull request closed without merging**
