### PR TITLE
List of user in group and team edition

### PR DESCRIPTION
**Pull request by alemannosara**

### CODE REVIEW

**Comment by alemannosara** [comment]
@fmutlu Thanks for noticing. I am fixing this now. I think it should be a problem of display so hopefully, I will merge today. 
Thanks for your review!

**Comment by nazliuzuner** [comment]
Everything seems really good to me (specially the test coverage :+1: ) .
Thank you !!

**Comment by alemannosara** [comment]
@fmutlu I have just fixed this. Hope this is fine for you.

@nazliuzuner Thank you !

**Comment by fmutlu** [comment]
> @fmutlu I have just fixed this. Hope this is fine for you.
> 
> @nazliuzuner Thank you !

Yes you can merge !

**Pull request merged**
