### PR TITLE
Display resume

### PR DESCRIPTION
**Pull request by alemannosara**
This PR let the user see the resume of another user.

A new bug was found which consists of the fact that uploading the resume only puts a 0 byte file on Firebase. I created a new issue (issue #199) for that purpose.

### CODE REVIEW

**Comment by fmutlu** [comment]
I noticed two things concerning UI : 

- When clicking on the back button we don't return to the profile but we close the app. This could be changed. 
- If the resume is not set the resume button is always visible. You can set its visibility to "View.GONE" so that the user doesn't try to click on it.  
A last thing, "Resume" doesn't appear as a clickable item. You can underline/put a color on it so that the user understands that it's clickable.  

Beside these points, everything is fine to me.

**Comment by alemannosara** [comment]
> I noticed two things concerning UI :
> 
> * When clicking on the back button we don't return to the profile but we close the app. This could be changed.
> * If the resume is not set the resume button is always visible. You can set its visibility to "View.GONE" so that the user doesn't try to click on it.
>   A last thing, "Resume" doesn't appear as a clickable item. You can underline/put a color on it so that the user understands that it's clickable.
> 
> Besides these points, everything is fine to me.

- The clicking back button is wanted actually. It is what @KnightEther did last week.

- Really? I checked on my computer and I cannot see it. 😩

- Yes, I will do so so that user know that it is clickable.

I have a question for you : namely I need help... I have a big bug, which happens when uploading a resume. Namely, the resume is on Firebase storage but has 0kB. However, I reread the code thousands of times and I have almost the same as you do for the profile picture. Do you think you could help me please?

**Comment by fmutlu** [comment]
> 
> 
> > I noticed two things concerning UI :
> > 
> > * When clicking on the back button we don't return to the profile but we close the app. This could be changed.
> > * If the resume is not set the resume button is always visible. You can set its visibility to "View.GONE" so that the user doesn't try to click on it.
> >   A last thing, "Resume" doesn't appear as a clickable item. You can underline/put a color on it so that the user understands that it's clickable.
> > 
> > Besides these points, everything is fine to me.
> 
>     * The clicking back button is wanted actually. It is what @KnightEther did last week.
> 
>     * Really? I checked on my computer and I cannot see it. 😩
> 
>     * Yes, I will do so so that user know that it is clickable.
> 
> 
> I have a question for you : namely I need help... I have a big bug, which happens when uploading a resume. Namely, the resume is on Firebase storage but has 0kB. However, I reread the code thousands of times and I have almost the same as you do for the profile picture. Do you think you could help me please?

Really ? It's really strange because I tried to upload a PDF and everything is fine by my side. The PDF is visible on Firebase and has 1.47 MB.

**Comment by alemannosara** [comment]
> > > I noticed two things concerning UI :
> > > 
> > > * When clicking on the back button we don't return to the profile but we close the app. This could be changed.
> > > * If the resume is not set the resume button is always visible. You can set its visibility to "View.GONE" so that the user doesn't try to click on it.
> > >   A last thing, "Resume" doesn't appear as a clickable item. You can underline/put a color on it so that the user understands that it's clickable.
> > > 
> > > Besides these points, everything is fine to me.
> > 
> > 
> > ```
> > * The clicking back button is wanted actually. It is what @KnightEther did last week.
> > 
> > * Really? I checked on my computer and I cannot see it. 😩
> > 
> > * Yes, I will do so so that user know that it is clickable.
> > ```
> > I have a question for you : namely I need help... I have a big bug, which happens when uploading a resume. Namely, the resume is on Firebase storage but has 0kB. However, I reread the code thousands of times and I have almost the same as you do for the profile picture. Do you think you could help me please?
> 
> Really ? It's really strange because I tried to upload a PDF and everything is fine by my side. The PDF is visible on Firebase and has 1.47 MB.

That's nice! Did you try when being on the branch of this PR?

**Comment by fmutlu** [comment]
> That's nice! Did you try when being on the branch of this PR?

Exactly.

**Comment by alemannosara** [comment]
> Exactly.

That's nice. Hence, I will work on the PR, try on my computer and modify the view of the text and check if I hide the link correctly when there's no resume available. Thanks!

**Comment by alemannosara** [comment]
@fmutlu I've just understood what you were talking about with the "press back". I thought you were talking about the upload part. Indeed, I have to do the press back also when you see the resume. Sorry about that!

**Comment by alemannosara** [comment]
@fmutlu I've just understood what you were talking about with the "press back". I thought you were talking about the upload part. Indeed, I have to do the press back also when you see the resume. Sorry about that!

**Comment by alemannosara** [comment]
@fmutlu I have just resolved the ProfileFragment problem we were talking about yesterday. I resolved the conflicts and did my best to keep your refactored code and add only the function needed for the resume but I think it could be fine if you could just read it to make sure I am not forgetting anything about the code you wrote. Thanks in advance and sorry for inconvenience

**Comment by fmutlu** [comment]
> 
> 
> @fmutlu I have just resolved the ProfileFragment problem we were talking about yesterday. I resolved the conflicts and did my best to keep your refactored code and add only the function needed for the resume but I think it could be fine if you could just read it to make sure I am not forgetting anything about the code you wrote. Thanks in advance and sorry for inconvenience

I took a look and all is fine. You can merge when you want.

**Comment by alemannosara** [comment]
@nazliuzuner I think I have the same problem as you did with candidatures : namely TRAVIS... What helped you to fix this problem?

**Comment by alemannosara** [comment]
@fmutlu It seems that the travis problem comes from the fast swipe of AddReferenceTest. Could you perhaps explain a bit how this swipeToBottomToTop works because I think I will need to refactor it to pass the build on travis?

**Comment by fmutlu** [comment]
> @fmutlu It seems that the travis problem comes from the fast swipe of AddReferenceTest. Could you perhaps explain a bit how this swipeToBottomToTop works because I think I will need to refactor it to pass the build on travis?

I'm not answering your question but I think that the problem arises from the fact that you changed the layout parameters of profile_description in fragment_profile.xml (especially the height which is not wrap_content anymore). I think that restoring them will solve your issue.

**Pull request merged**
